"""Initial migration

Revision ID: 3b7ea4429f4a
Revises: 
Create Date: 2024-07-03 02:21:16.833751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7ea4429f4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_notes', sa.Text(), nullable=True))
        batch_op.alter_column('ecg_data',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostic', schema=None) as batch_op:
        batch_op.alter_column('ecg_data',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('patient_notes')

    # ### end Alembic commands ###
